---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  EIP1:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
  EIP2:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
  EIP3:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc

Outputs:
  EIP1:
    Description: 'EIP for NAT instance1'
    Value: !GetAtt EIP1.AllocationId
    Export:
      Name: EIP1AllocationId
  EIP2:
    Description: 'EIP for NAT instance2'
    Value: !GetAtt EIP2.AllocationId
    Export:
      Name: EIP2AllocationId
  EIP3:
    Description: 'EIP for NAT instance3'
    Value: !GetAtt EIP3.AllocationId
    Export:
      Name: EIP3AllocationId