---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  NATGWASubnet:
    Description: 'Subnet for NAT gateway in AZ1'
    Type: AWS::EC2::Subnet::Id
  NATGWBSubnet:
    Description: 'Subnet for NAT gateway in AZ2'
    Type: AWS::EC2::Subnet::Id
  NATGWCSubnet:
    Description: 'Subnet for NAT gateway in AZ3'
    Type: AWS::EC2::Subnet::Id

Metadata:
  ParameterLabels:
    - NATGWSubnetA:
        default: 'Subnet for NAT gateway on AZ1'
    - NATGWSubnetB:
        default: 'Subnet for NAT gateway on AZ2'
    - NATGWSubnetC:
        default: 'Subnet for NAT gateway on AZ3'
  ParameterGroups:
    - Label:
        default: 'Select only public subnets on different AZs for NAT gateways'
      ParameterGroups:
        - NATGWASubnet
        - NATGWBSubnet
        - NATGWCSubnet

Resources:
  NATGWA:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !ImportValue EIP1AllocationId
      SubnetId: !Ref NATGWASubnet
      Tags:
        - Key: 'Name'
          Value: !Join ['-',[!Ref 'AWS::StackName','NATGWA']]
  NATGWB:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !ImportValue EIP2AllocationId
      SubnetId: !Ref NATGWBSubnet
      Tags:
        - Key: 'Name'
          Value: !Join ['-',[!Ref 'AWS::StackName','NATGWB']]
  NATGWC:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !ImportValue EIP2AllocationId
      SubnetId: !Ref NATGWCSubnet
      Tags:
        - Key: 'Name'
          Value: !Join ['-',[!Ref 'AWS::StackName','NATGWC']]

Outputs:
  NatGatewayA:
    Description: 'NAT gateway for private instances in AZ1'
    Value: !Ref NATGWA
    Export:
      Name: 'NatGatewayA'
  NatGatewayB:
    Description: 'NAT gateway for private instances in AZ2'
    Value: !Ref NATGWB
    Export:
      Name: 'NatGatewayB'
  NatGatewayC:
    Description: 'NAT gateway for private instances in AZ3'
    Value: !Ref NATGWC
    Export:
      Name: 'NatGatewayC'